using System;
using System.Collections.Generic;

namespace meridian.diagram
{
    public class CodeFile : BasicFile
    {
        public CodeFile()
        {
            Usings = new List<string>();
            Usings.Add("System");
            Usings.Add("System.Linq");
            Usings.Add("System.Text");
            Usings.Add("System.Data.Linq");
         //   Usings.Add("System.Data.SqlClient");
            Usings.Add("System.Collections.Generic");
        }


        public virtual void WriteInners(CSharpWriter _writer)
        {

        }

        public override void WriteCode(CSharpWriter writer)
        {
            base.WriteCode(writer);
            writer.WriteLine("/* Automatically generated codefile, Meridian");
            writer.WriteLine(" * Generated by magic, please do not interfere");
            writer.WriteLine(" * Please sleep well and do not smoke. Love, Sam */");
            writer.WriteLine("");

            foreach (var u in Usings)
            {
                writer.WriteUsing(u);
            }

            writer.WriteBlank();

            writer.WriteNamespace(Namespace);

            writer.OpenBlock();

            WriteInners(writer);

            writer.CloseBlock();
        }

        
        public List<string> Usings { get; set; }
        public string Namespace { get; set; }


    }
}